CREATE TABLE event_metadata (
  ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EVENT_ID int(11) NOT NULL,
  ACADEMIC_YEAR varchar(10) DEFAULT NULL,
  SEASON varchar(10) DEFAULT NULL,
  SEM int(11) DEFAULT NULL,
  SECTION varchar(10) DEFAULT NULL,
  SUBJECT_CODE varchar(15) DEFAULT NULL,
  SUBJECT varchar(100) DEFAULT NULL,
  PARTICULAR varchar(50) DEFAULT NULL,
  REGISTRATION_DEADLINE datetime DEFAULT NULL,
  PARTICIPATION_TYPE varchar(20) DEFAULT 'solo',
  MAX_PARTICIPANTS int(11) DEFAULT NULL,
  MAX_TEAM_SIZE int(11) DEFAULT NULL,
  MAX_VOLUNTEERS int(11) DEFAULT NULL,
  MAX_COORDINATORS int(11) DEFAULT NULL,
  BROUCHER longtext DEFAULT NULL,
  ATTACHMENTS longtext DEFAULT NULL,
  POST_EVENT_REPORT text DEFAULT NULL,
  REPORT_PDF_PATH varchar(500) DEFAULT NULL,
  DETAILS_JSON json DEFAULT NULL,
  REMARKS varchar(500) DEFAULT NULL,
  APPROVAL_ROUTE varchar(500) DEFAULT NULL,
  APPROVAL_STEP int(11) DEFAULT 0,
  APPROVAL_HISTORY_JSON json DEFAULT NULL,
  BUDGET decimal(10,2) DEFAULT NULL,
  SUB_EVENT_ID varchar(255) DEFAULT NULL,
  SUB_EVENT_NAME varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO event_metadata (
  EVENT_ID, ACADEMIC_YEAR, SEASON, SEM, SECTION, SUBJECT_CODE, SUBJECT, PARTICULAR,
  REGISTRATION_DEADLINE, PARTICIPATION_TYPE, MAX_PARTICIPANTS, MAX_TEAM_SIZE, MAX_VOLUNTEERS, MAX_COORDINATORS,
  BROUCHER, ATTACHMENTS, POST_EVENT_REPORT, REPORT_PDF_PATH, DETAILS_JSON, REMARKS,
  APPROVAL_ROUTE, APPROVAL_STEP, APPROVAL_HISTORY_JSON, BUDGET, SUB_EVENT_ID, SUB_EVENT_NAME
)
SELECT 
  SL_NO, ACADEMIC_YEAR, SEASON, SEM, SECTION, SUBJECT_CODE, SUBJECT, PARTICULAR,
  REGISTRATION_DEADLINE, PARTICIPATION_TYPE, MAX_PARTICIPANTS, MAX_TEAM_SIZE, MAX_VOLUNTEERS, MAX_COORDINATORS,
  BROUCHER, ATTACHMENTS, POST_EVENT_REPORT, REPORT_PDF_PATH, DETAILS_JSON, REMARKS,
  APPROVAL_ROUTE, APPROVAL_STEP, APPROVAL_HISTORY_JSON, BUDGET, SUB_EVENT_ID, SUB_EVENT_NAME
FROM event_master;

ALTER TABLE event_master 
  DROP COLUMN ACADEMIC_YEAR,
  DROP COLUMN SEASON,
  DROP COLUMN SEM,
  DROP COLUMN SECTION,
  DROP COLUMN SUBJECT_CODE,
  DROP COLUMN SUBJECT,
  DROP COLUMN PARTICULAR,
  DROP COLUMN REGISTRATION_DEADLINE,
  DROP COLUMN PARTICIPATION_TYPE,
  DROP COLUMN MAX_PARTICIPANTS,
  DROP COLUMN MAX_TEAM_SIZE,
  DROP COLUMN MAX_VOLUNTEERS,
  DROP COLUMN MAX_COORDINATORS,
  DROP COLUMN BROUCHER,
  DROP COLUMN ATTACHMENTS,
  DROP COLUMN POST_EVENT_REPORT,
  DROP COLUMN REPORT_PDF_PATH,
  DROP COLUMN DETAILS_JSON,
  DROP COLUMN REMARKS,
  DROP COLUMN APPROVAL_ROUTE,
  DROP COLUMN APPROVAL_STEP,
  DROP COLUMN APPROVAL_HISTORY_JSON,
  DROP COLUMN BUDGET,
  DROP COLUMN SUB_EVENT_ID,
  DROP COLUMN SUB_EVENT_NAME;
