-- =============================================================
-- GMU_Events01 — Unified Database for both projects
-- Run this on the HOST machine (your machine)
-- =============================================================

CREATE DATABASE IF NOT EXISTS `GMU_Events01`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `GMU_Events01`;

-- 1. UNIFIED USERS TABLE
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `usn_or_emp_id` VARCHAR(50) DEFAULT NULL,
  `username` VARCHAR(100) UNIQUE DEFAULT NULL,
  `full_name` VARCHAR(200) DEFAULT NULL,
  `email` VARCHAR(200) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) DEFAULT NULL,
  `system_role` ENUM('student','faculty','hod','director','dean','pro_vc','vc','admin','events_admin','volunteer') DEFAULT 'student',
  `role` VARCHAR(50) DEFAULT 'student',
  `department` VARCHAR(100) DEFAULT NULL,
  `faculty_name` VARCHAR(255) DEFAULT NULL,
  `school_name` VARCHAR(255) DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. UNIFIED EVENT MASTER TABLE
CREATE TABLE IF NOT EXISTS `event_master` (
  `SL_NO` INT AUTO_INCREMENT PRIMARY KEY,
  `EVENT_ID` VARCHAR(255) UNIQUE NOT NULL,
  `DEPARTMENT` VARCHAR(100) NOT NULL,
  `CATEGORY` VARCHAR(50) NOT NULL,
  `TYPE` VARCHAR(50) NOT NULL,
  `MODE` VARCHAR(50) NOT NULL,
  `EVENT` VARCHAR(200) NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NOT NULL,
  `START_TIME` TIME DEFAULT NULL,
  `END_TIME` TIME DEFAULT NULL,
  `VENUE` VARCHAR(255) DEFAULT NULL,
  `COORDINATOR` VARCHAR(100) DEFAULT NULL,
  `CONTACT` VARCHAR(50) DEFAULT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` INT NOT NULL,
  `STATUS` VARCHAR(50) DEFAULT 'active',
  `CURRENT_STATUS` VARCHAR(100) DEFAULT 'pending',
  `EVENT_SCALE` VARCHAR(50) DEFAULT NULL,
  `IMMEDIATE_APPROVAL` TINYINT(1) DEFAULT 0,
  `faculty` VARCHAR(255) DEFAULT NULL,
  `school` VARCHAR(255) DEFAULT NULL,
  `is_archived` TINYINT(1) DEFAULT 0,
  `organizer_id` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. UNIFIED EVENT METADATA TABLE
CREATE TABLE IF NOT EXISTS `event_metadata` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `EVENT_ID` INT NOT NULL,
  `ACADEMIC_YEAR` VARCHAR(10) DEFAULT NULL,
  `SEASON` VARCHAR(10) DEFAULT NULL,
  `SEM` INT DEFAULT NULL,
  `SECTION` VARCHAR(10) DEFAULT NULL,
  `SUBJECT_CODE` VARCHAR(15) DEFAULT NULL,
  `SUBJECT` VARCHAR(100) DEFAULT NULL,
  `PARTICULAR` VARCHAR(50) DEFAULT NULL,
  `REGISTRATION_DEADLINE` DATETIME DEFAULT NULL,
  `PARTICIPATION_TYPE` VARCHAR(20) DEFAULT NULL,
  `MAX_PARTICIPANTS` INT DEFAULT NULL,
  `MAX_TEAM_SIZE` INT DEFAULT 1,
  `MAX_VOLUNTEERS` INT DEFAULT NULL,
  `MAX_COORDINATORS` INT DEFAULT NULL,
  `BROUCHER` LONGTEXT DEFAULT NULL,
  `ATTACHMENTS` LONGTEXT DEFAULT NULL,
  `POST_EVENT_REPORT` TEXT DEFAULT NULL,
  `REPORT_PDF_PATH` VARCHAR(500) DEFAULT NULL,
  `DETAILS_JSON` JSON DEFAULT NULL,
  `REMARKS` VARCHAR(500) DEFAULT NULL,
  `APPROVAL_ROUTE` VARCHAR(500) DEFAULT NULL,
  `APPROVAL_STEP` INT DEFAULT 0,
  `APPROVAL_HISTORY_JSON` JSON DEFAULT NULL,
  `BUDGET` DECIMAL(10,2) DEFAULT 0.00,
  `SUB_EVENT_ID` VARCHAR(255) DEFAULT NULL,
  `SUB_EVENT_NAME` VARCHAR(255) DEFAULT NULL,
  `chat_history` JSON DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. UNIFIED EVENT REGISTRATIONS TABLE
CREATE TABLE IF NOT EXISTS `event_registrations` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `STUDENT_ID` VARCHAR(50) DEFAULT NULL,
  `user_id` INT DEFAULT NULL,
  `EVENT_ID` INT NOT NULL,
  `SUB_EVENT_ID` VARCHAR(80) DEFAULT NULL,
  `REGISTRATION_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `STATUS` ENUM('active','completed') DEFAULT 'active',
  `ROLE` ENUM('participant','volunteer','coordinator','organiser') DEFAULT 'participant',
  `CERTIFICATE_URL` VARCHAR(500) DEFAULT NULL,
  `FEEDBACK_RATING` TINYINT DEFAULT NULL,
  `FEEDBACK_COMMENTS` TEXT DEFAULT NULL,
  `feedback_text` TEXT DEFAULT NULL,
  `feedback_submitted` TINYINT(1) DEFAULT 0,
  `QR_TOKEN` VARCHAR(255) DEFAULT NULL,
  `qr_code` VARCHAR(255) DEFAULT NULL,
  `SPECIAL_REQUIREMENTS` TEXT DEFAULT NULL,
  `CHECK_IN_STATUS` ENUM('pending','checked_in') DEFAULT 'pending',
  `attendance_status` VARCHAR(50) DEFAULT 'Pending',
  `attended` TINYINT(1) DEFAULT 0,
  `CHECK_IN_TIME` DATETIME DEFAULT NULL,
  `details_json` JSON DEFAULT NULL,
  `TEAM_LEAD` VARCHAR(100) DEFAULT NULL,
  `TEAM_MEMBERS` TEXT DEFAULT NULL,
  `IS_EXTERNAL` TINYINT(1) DEFAULT 0,
  `COLLEGE_NAME` VARCHAR(255) DEFAULT NULL,
  `PHONE` VARCHAR(20) DEFAULT NULL,
  `EMAIL` VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. UNIFIED NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` VARCHAR(50) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `target_link` VARCHAR(255) DEFAULT NULL,
  `is_read` TINYINT(1) DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. UNIFIED APPROVAL RULES TABLE
CREATE TABLE IF NOT EXISTS `approval_rules` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `scale_name` VARCHAR(100) DEFAULT NULL,
  `event_type` VARCHAR(100) DEFAULT NULL,
  `level` INT DEFAULT NULL,
  `role` VARCHAR(100) DEFAULT NULL,
  `role_name` VARCHAR(100) DEFAULT NULL,
  `required_chain` JSON DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'GMU_Events01 created and all 6 tables ready!' AS status;
